name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
# inputs:
#   milliseconds: # change this
#     required: true
#     description: 'input description here'
#     default: 'default value if applicable'
# runs:
#   using: 'node16'
#   main: 'dist/index.js'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash