name: 'test-fabric-gh'
description: 'CI/CD'
author: 'Tapestry Labs'
# inputs:
#   projectId:
#     required: true
#     description: 'input description here'
runs:
  using: "composite"
  steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/728919945741/locations/global/workloadIdentityPools/fabric/providers/github'
        service_account: 'dev-104@fabric-375222.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
    - id: 'gcloud'
      name: 'gcloud'
      shell: bash
      run: |-
        gcloud services list